### ISSUE TITLE
Culture related formatting for decimal numbers

### ISSUE THREAD

**Issue by KristofferStrube** [petabridge/DrawTogether.NET#11]
Many countries in the world have other decimal separators than the dot sign like a comma in most of Europe, South America, and some of Africa. SVG elements expect decimal numbers with a dot separator, but when running the application the local CultureInfo is used, so it will use a comma instead, for some. To fix this globally for your Blazor Wasm project, you can add the following to that project file:
```xml
<PropertyGroup>
  <InvariantGlobalization>true</InvariantGlobalization>
</PropertyGroup>
```

**Comment by Aaronontheweb** [comment]
Good idea
